---
title: "Accessing the GHSI Tools"
description: |
  Short Form Measures from the GHSI
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Licensing
The GHSI tools are free to use for research, treatment, and non-commercial purposes. If you are interested in using our tools, please:


1. Review the [GHSI License Agreement (Word format, 0.1MB)](files/GHSI_License.docx)
2. Contact the [research team](mailto:ryan.statton@plymouth.ac.uk,james.close@plymouth.ac.uk?subject=GHSI%20Inquiry) to discuss your intended use and complete the registration process


---

# GHSI

There are a number of versions of the GHSI available, for both people who gamble and affected others. For the development and validation process, please see our [Research Outputs](papers.html).
The GHSI has been mapped to decrements in health utility, enabling health economic assessment. To see how the conversion work, please see our [“Conversion Calculator”](converter.html).
 

**The Gambling Harms Severity Index - 10 items (GHSI-10)**

A ten-item version of the scale. The first 7 items assess experiences of harm from our [Framework](framework.html) across the 3 major components: Wellbeing, Resources, and Relationships. A final 3 additional items assess experiences of higher order harms (such as suicidal thoughts) in the 3 components.  The GHSI-10 is designed for face-to-face settings, where an expert service provider or clinician is in conversation with a client. All items are scored from 0-3. Total scores range between 0 and 30, higher scores indicate a greater experience of harm.

[Download GHSI-10 (PDF format, 0.9MB)](files/GHSI-10.pdf). 


**The Gambling Harms Severity Index - 7 items (GHSI-7)**

The seven-item version of the scales does not include the three higher harm items at the end, and is therefore more applicable in situations where safeguarding is not such a concern, such as online use. All items are scored from 0-3. Total scores range between 0 and 21, higher scores indicate a greater experience of harm.


[Download GHSI-7 (PDF format, 0.9MB)](files/GHSI-7.pdf). 


**The Gambling Harms Severity Index - 3 items (GHSI-3)**

This version is a short screening tool where brevity is essential, such as preliminary screening for harms.


[Download GHSI-3 (PDF format, 0.9MB)](files/GHSI-3.pdf). 


---

# GHSI-AO

The GHSI for Affected Others (GHSI-AO) has been co-designed with affected others, treatment and service providers, and those with lived experience of gambling-related harms. It exists in two versions: - the GHSI-AO-7 for online screening and monitoring - the GHSI-AO-10 for face-to-face consultation with service providers and treatment professionals
GHSI-AO is designed to be delivered either in person or online, the measure is suitable for people experiencing gambling-related harms as a result of someone else’s gambling at all stages of their personal recovery journey. It is not a measure of harm or recovery in the person that gambles.


**The GHSI for Affected Others - 10 items (GHSI-AO-10)**

A ten-item version of the scale, which mirrors the GSHI but reworded with the emphasis re-targeted at the issues that affected others face. The GHSI-10-AO is designed for face-to-face settings, where an expert service provider or clinician is in conversation with a client. 



[Download GHSI-AO-10 (PDF format, 0.8MB)](files/GHSI-AO-10.pdf). 


**The GHSI for Affected Others - 7 (GHSI-AO-7)**

A seven-item version that does not include the three higher harm items at the end, and is therefore more applicable in situations where safeguarding is not such a concern, such as online use.


[Download GHSI-AO-7 (PDF format, 0.8MB)](files/GHSI-AO-7.pdf). 


 
---

# GHSI-Recovery
**A Holistic Tool for Measuring Recovery from Gambling-Related Harms**

GHSI-Recovery has been co-designed with people who have lived experience of gambling-related harms, service and treatment providers, and affected others. It draws from the tenets of Positive Psychology and Recovery Capital to focus on the journey of recovery. Items are worded such that they focus on moving forwards and building capacity, capability, and resilience. 

The GHSI-Recovery is a 10 item measure of recovery from gambling-related harms. The first 6 items assess recovery from harms that align with the components of recovery capital from our [Framework](framework.html). The final 4 items assess the drivers and enablers of recovery. Designed to be delivered either in person or online, the measure is suitable for people experiencing gambling-related harms at all stages of their personal recovery journey. 

[Download GHRI-R (PDF format, 0.7MB)](files/GHSI-Recovery.pdf). 
